###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Comeau, CS165
# Author:
#     Brendon Marques
# Summary:
#     This program will prompt the user for information of the
#     product to be added to the inventory. Then, it will
#     prompt the user for a display option, and it will display
#     the product according to the user's preferences.. 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

