###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Comeau, CS165
# Author:
#     Brendon Marques
# Summary:
#     This program is ana expansion of last week's program.
#	   However, this time the program will handle products,
#     as well as costumers, addresses and orders. 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

